#!/usr/bin/env bash

docker create -it \
  --name cuda-samples \
  --mount type=bind,source="$(pwd)",target=/workspace \
  --mount type=bind,source=/etc/localtime,target=/etc/localtime,readonly \
  --runtime=nvidia \
  --gpus all \
  brikex/cuda_samples:latest bash
