FROM nvidia/cuda:12.2.2-cudnn8-devel-ubuntu22.04

WORKDIR /workspace

RUN apt-get update
RUN apt-get install -y git vim cmake
RUN apt-get install -y curl zip unzip
RUN apt-get install -y python3 python3-pip
